### ISSUE TITLE
dropbox.exceptions.ApiError: ApiError

### ISSUE THREAD

**Issue by turkeyphant** [H4KKR/AutoYouTubeLikeDownloader#1]
As others have said, there is no way to change the App folder name in the Dropbox App Console. As a result I have the following settings:

![Screenshot 2020-07-22 18 52 09](https://user-images.githubusercontent.com/8129583/88210739-8e960a80-cc4c-11ea-9c66-e68b68670301.png)

Your instructions say to use the name "YouTube" but there's no reference to this I can find in the code.

And when I run it anyway, I just get:

```
$ python3 YTDownloader.py 
Waiting for an internet connection...
Connection OK
Connecting to Dropbox...
Searching for link...
Like found! Checking against stored URLs..
Traceback (most recent call last):
  File "YTDownloader.py", line 89, in <module>
    main()
  File "YTDownloader.py", line 58, in main
    URLs =  digest(downloadFile(dbx=dbx, folder=folderPath, name=fileName).decode('utf-8').split('\n'))
  File "YTDownloader.py", line 31, in downloadFile
    md, res = dbx.files_download(path)
  File "/usr/lib64/python3.8/site-packages/dropbox/base.py", line 1475, in files_download
    r = self.request(
  File "/usr/lib64/python3.8/site-packages/dropbox/dropbox.py", line 337, in request
    raise ApiError(res.request_id,
dropbox.exceptions.ApiError: ApiError('hexhexhex', DownloadError('path', LookupError('not_found', None)))
```

**Comment by H4KKR** [comment]
Have you tried it with the new code?

**Comment by ColdLunaris** [comment]
Have you tried changing the path on IFTTT to the name of your folder? You can find your DropBox-path by going to the root of your DropBox-folder and clicking your way through.

Also notice how for different languages you might not have a folder named "Apps", but your languages equivalent. I got it working when I changed this. 
![image](https://user-images.githubusercontent.com/56576378/88226431-58688300-cc6c-11ea-98a5-791a8e5c02a4.png)

**Comment by H4KKR** [comment]
Right, perfect thank you! I'll make sure to add this in to the instructions.

And a big thanks for my first ever issue on Github!! Seriously, I'm still in school and it means a lot to have a community help me with projects. Keep contributing turkeyphant!!

**Comment by turkeyphant** [comment]
> Have you tried it with the new code?

Just did a git pull and got this:

```
REPLACED ILLEGAL CHARACTERS IN VIDEO TITLE
DOWNLOADING VIDEO...
DOWNLOADING AUDIO...
Traceback (most recent call last):
  File "YTDownloader.py", line 183, in <module>
    LocalMain(FETCH_FILE_NAME, PREV_TXT_PATH, DOWNLOAD_PATH, RES)
  File "YTDownloader.py", line 172, in LocalMain
    main(Local.fetchNewFileData(), DOWNLOAD_PATH, RES)
  File "YTDownloader.py", line 161, in main
    downloadVideoBEST(i, DOWNLOAD_PATH)
  File "YTDownloader.py", line 113, in downloadVideoBEST
    va = ffmpeg.input(f'{path}tmp/audio.mp4')
AttributeError: module 'ffmpeg' has no attribute 'input'
```

edit 1: Just realised I may need to install ffmpeg now. Bear with me.

edit 2: can't work out how to install it on unraid

**Comment by turkeyphant** [comment]
> Have you tried changing the path on IFTTT to the name of your folder? 

Yes I did that. But I understand it's not relevant int he latest version.

**Comment by ColdLunaris** [comment]
You can avoid using ffmpeg by simply removing it from the first line in the script. Beware that this makes downloading at max quality won't work, but by default this isn't enabled, so this shouldn't be an issue. The main dev could change the script to only require ffmpeg if you activate max quality in the config-file

**Comment by turkeyphant** [comment]
Annoying, I do need max.

**Comment by ColdLunaris** [comment]
Then you should be able to install it using 'pip3 install ffmpeg' or 'pip3 install ffmpeg-python'.

**Comment by turkeyphant** [comment]
Derp, now the the IFTTT isn't even running. It created the folder but not the text file. How long does it usually take after liking?

**Comment by ColdLunaris** [comment]
Honestly, no idea. Some redditors say it can take between 15-30 minutes, but only IFTTT knows this

**Comment by turkeyphant** [comment]
It's now been several hours and it hasn't run once.
